<?php
$form = $this->form;
$form->setAttribute('method', 'POST');
$form->setAttribute('action', $this->url('submit-form3'));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title py-2">Loan details</h4>

          <div class="form-group mt-3 mb-3">
            <?php
            $form->get('loan_amount')->setAttributes([
              'class' => 'form-control',
              'placeholder' => 'loan amount (£)',
              'required' => 'required'
            ]);
            echo $this->formElement($form->get('loan_amount'));
            ?>
          </div>

          <div class="form-group mt-3 mb-3 d-flex mx-1 align-items-center">
            <label for="loan_duration" class="text-secondary">loan duration</label>
            <input type="range" class="custom-range mx-1" id="loan_duration" name="loan_duration" min="0" max="60" step="12" value="0" oninput="loanDurationOutput.value = this.value + ' months'" style="width: 57%;">
            <output id="loanDurationOutput" class="text-secondary mx-1"><span class="text-secondary">0 months</span></output>
          </div>

          <div class="form-group mt-3">
            <div class="card">
              <div class="card-body">
              <h6 class="pb-2">Reason for loan</h6>
                <?php
                $loanReasonElement = $form->get('loan_reason');
                $valueOptions = $loanReasonElement->getValueOptions();
                foreach ($valueOptions as $value => $label) {
                  $radioId = 'loan_reason_' . $value;
                ?>
                  <div class="form-check mb-2">
                    <input type="radio" class="form-check-input" name="loan_reason" id="<?= $radioId ?>" value="<?= $value ?>" required>
                    <label class="form-check-label" for="<?= $radioId ?>"><?= $label ?></label>
                  </div>
                <?php
                }
                ?>
              </div>
            </div>
          </div>

          <?php
          echo $this->formElement($form->get('csrf'));
          ?>

          <div class="d-flex justify-content-end">
            <?php
            $form->get('submit')->setAttribute('class', 'btn btn-outline-secondary bg-gradient mt-3');
            echo $this->formElement($form->get('submit'));
            ?>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<?php
echo $this->form()->closeTag();
?>