<?php
$form = $this->form;
$form->setAttribute('method', 'POST');
$form->setAttribute('action', $this->url('submit-form4'));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title py-2">Contact me</h4>

          <div class="form-group mt-3 mb-3">
            <?php
            $form->get('contact_name')->setAttributes([
              'class' => 'form-control',
              'placeholder' => 'full name',
              'required' => 'required'
            ]);
            echo $this->formElement($form->get('contact_name'));
            ?>
          </div>

          <div class="form-group mt-3 mb-3">
            <?php
            $form->get('contact_email')->setAttributes([
              'class' => 'form-control',
              'placeholder' => 'email',
              'required' => 'required'
            ]);
            echo $this->formElement($form->get('contact_email'));
            ?>
          </div>

          <div class="form-group mt-3">
            <?php
            $form->get('contact_message')->setAttributes([
              'class' => 'form-control',
              'placeholder' => 'message',
              'required' => 'required',
              'rows' => 5
            ]);
            echo $this->formElement($form->get('contact_message'));
            ?>
          </div>

          <!-- COMMENT OUT UNTIL VALIDATION WORKS -->
          <!--
          <div class="form-group mt-3">
            <label class="text-secondary"> $this->translate('') ?></label>
             $this->formElement($form->get('captcha')) ?>
          </div>
          -->

          <?php
          echo $this->formElement($form->get('csrf'));
          ?>

          <div class="d-flex justify-content-end">
            <?php
            $form->get('submit')->setAttribute('class', 'btn btn-outline-secondary bg-gradient mt-3');
            echo $this->formElement($form->get('submit'));
            ?>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<?php
echo $this->form()->closeTag();
?>