<?php
$form = $this->form;
$form->setAttribute('method', 'POST');
$form->setAttribute('action', $this->url('submit-form5'));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title py-2">Equal opportunities</h4>

          <div class="form-group mt-3 mb-3">
            <?= $this->formSelect($form->get('gender')->setValueOptions([
              '' => $form->get('gender')->getLabel(),
              'male' => 'Male',
              'female' => 'Female',
              'other' => 'Other',
              'prefer_not_to_say' => 'Prefer not to say',
            ])->setAttributes([
              'class' => 'form-control'
            ])); ?>
          </div>

          <div class="form-group mt-3 mb-3">
            <?= $this->formSelect($form->get('ethnicity')->setValueOptions([
              '' => $form->get('ethnicity')->getLabel(),
              'white' => 'White',
              'black' => 'Black',
              'asian' => 'Asian',
              'mixed' => 'Mixed/Multiple ethnic groups',
              'other' => 'Other ethnic group',
              'prefer_not_to_say' => 'Prefer not to say',
            ])->setAttributes([
              'class' => 'form-control'
            ])); ?>
          </div>

          <div class="form-group mt-3 mb-3">
            <div class="card">
              <div class="card-body">
                <h6 class="pb-2"><?= $this->escapeHtml($form->get('disability')->getLabel()); ?></h6>

                <?php
                $disabilityElement = $form->get('disability');
                $valueOptions = $disabilityElement->getValueOptions();
                foreach ($valueOptions as $value => $label) {
                  $radioId = 'disability_' . $value;
                ?>
                  <div class="form-check mb-2">
                    <input type="radio" class="form-check-input" name="disability" id="<?= $radioId ?>" value="<?= $value ?>" required>
                    <label class="form-check-label" for="<?= $radioId ?>"><?= $label ?></label>
                  </div>
                <?php
                }
                ?>
              </div>
            </div>
          </div>


          <?php
          echo $this->formElement($form->get('csrf'));
          ?>

          <div class="d-flex justify-content-end">
            <?= $this->formElement($form->get('submit')->setAttribute('class', 'btn btn-outline-secondary bg-gradient mt-3')); ?>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<?= $this->form()->closeTag(); ?>