<?php
$form = $this->form;
$form->setAttribute('method', 'POST');
$form->setAttribute('action', $this->url('submit-form1'));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title py-2">Sign up</h4>

          <div class="form-group mt-3 mb-3">
            <?php
            $form->get('first_name')->setAttributes([
              'class' => 'form-control',
              'placeholder' => 'first name',
              'required' => 'required'
            ]);
            echo $this->formElement($form->get('first_name'));
            ?>
          </div>

          <div class="form-group mt-3 mb-3">
            <?php
            $form->get('last_name')->setAttributes([
              'class' => 'form-control',
              'placeholder' => 'last name',
              'required' => 'required'
            ]);
            echo $this->formElement($form->get('last_name'));
            ?>
          </div>

          <div class="form-group mt-3">
            <?php
            $form->get('email')->setAttributes([
              'class' => 'form-control',
              'placeholder' => 'email',
              'required' => 'required'
            ]);
            echo $this->formElement($form->get('email'));
            ?>
          </div>

          <?php
          echo $this->formElement($form->get('csrf'));
          ?>

          <div class="d-flex justify-content-end">
            <?php
            $form->get('sign_up')->setAttribute('class', 'btn btn-outline-secondary bg-gradient mt-3');
            echo $this->formElement($form->get('sign_up'));
            ?>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<?php
echo $this->form()->closeTag();
?>